name: svgaplayer_flutter
description: The SVGAPlayer implementation of Flutter using CustomPainter.
version: 1.3.0
author: PonyCui<ponycui@me.com>
homepage: https://github.com/yyued/SVGAPlayer-Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.0
  http: ^0.13.1
  path_drawing: ^0.5.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
