name: svgaplayer_flutter
description: The SVGAPlayer implementation of Flutter using CustomPainter.
version: 1.2.0
author: PonyCui<ponycui@me.com>
homepage: https://github.com/yyued/SVGAPlayer-Flutter

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^1.1.3
  http: ^0.12.2
  path_drawing: ^0.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
